// Public acquisition facts checked against Studio configuration and reward handlers.
const AD=ACQUISITION_DATA;
const itemName=id=>WIKI_CATALOG.items.find(x=>x.id===id)?.name||readable(id);
const itemCell=id=>({text:itemName(id),id:itemIds.get(id)});
const costsText=(costs={})=>Object.entries(costs).map(([id,n])=>`${fmt(n)} ${itemName(id)}`).join(' + ');
function obtain(id,label,detail,route){const a=existingId.get(itemIds.get(id)||id);if(!a)return;a.obtaining??=[];a.obtaining.push([{text:label,id:route},detail]);}
function tableFor(a,title,headers,rows,note){a.tables??=[];a.tables.push({title,headers,rows,note});}
CATEGORIES.find(c=>c[0]==='shops')[1]='Shops';
CATEGORIES.splice(CATEGORIES.findIndex(c=>c[0]==='shops')+1,0,['gear','Equipment','']);
CATEGORY_COPY.shops='Visit each shop to see its own inventory, honey prices, and material costs.';
CATEGORY_COPY.gear='Compare tools, bags, hats, and wearable gear. Each item links to the shops that sell it.';
for(const a of ARTICLES)if(a.category==='shops')a.category='gear';
const shopLists=[
 {id:'starter-shop',name:'Starter Shop',location:'Starter location',stock:{tools:['FlowerBrush','HoneyRake','TinPollenScooper','NetScooper'],bags:['SchoolBackpack','HoneyBag','HeavyBackpack','BloomSatchel'],hats:['TinfoilHat','SproutGoggles'],gear:['Resin Boots','Left Mud Shoulder','Right Mud Shoulder','Leafy Belt']}},
 {id:'rocky-shop',name:'Rocky Shop',location:'Rocky location',stock:{tools:['TinPollenScooper','LeafCutter'],bags:['HeavyBackpack','BloomSatchel'],hats:['TinfoilHat','SproutGoggles']}}
];
for(const shop of shopLists){addEntry({id:shop.id,title:shop.name,category:'shops',type:'Equipment shop',summary:`Browse the gear sold in the ${shop.location.toLowerCase()}.`,facts:[['Location',shop.location]],sections:[],source:sourceLabel('ShopManager inventory filters, ToolConfig, BagsConfig, HatConfig and GearData')});const a=existingId.get(shop.id);for(const [kind,names] of Object.entries(shop.stock)){const rows=[];for(const id of names){const v=AD[kind][id];if(!v||v.ShopVisible===false)continue;const route=slug(v.DisplayName);rows.push([{text:v.DisplayName,id:route},v.Rarity,fmt(v.Price)+' honey',costsText(v.ItemCosts)||'None']);obtain(route,shop.name,fmt(v.Price)+' honey'+(v.ItemCosts?' + '+costsText(v.ItemCosts):''),shop.id);existingId.get(route)?.related.push(shop.id)}tableFor(a,readable(kind),['Gear','Rarity','Honey price','Materials'],rows)}a.related=['equipment'];}
existingId.get('strawberry-hat').sections.push(['Availability','Hidden from shop listings in the current configuration. No confirmed purchase source was found.']);
function supplyShop(id,title,summary,rows){addEntry({id,title,category:'shops',type:'Supply shop',summary,facts:[['Stock',rows.length+' offers']],sections:[],source:sourceLabel('Shop configuration and purchase handler')});tableFor(existingId.get(id),'Stock',['Item / offer','Quantity','Price'],rows);}
supplyShop('normal-egg-shop','Normal Egg Shop','Stand on the Normal Egg purchase platform to buy an egg. Prices rise with your purchase count.',[[itemCell('egg_normal'),'1','Starts at 2,500 honey; purchase 5: 50,000; purchase 10: 1,000,000; purchase 15 onward: 33,000,000.']]);
obtain('egg_normal','Normal Egg Shop','Buy one at a time; starts at 2,500 honey and rises with purchases.','normal-egg-shop');
supplyShop('jel-shop','Jel Shop','Stand on the Jel purchase platform. Each successive Jel costs 500 more honey, capped at 700,000 per Jel.',[[itemCell('Jel'),'1, 10, 100, 1,000 or 10,000','Starts at 50,000 honey per Jel. Batches sum the successive unit prices.']]);
obtain('Jel','Jel Shop','Buy for honey: starts at 50,000 per Jel, +500 per purchase, capped at 700,000 each.','jel-shop');
supplyShop('autumn-shop','Autumn Harvest Shop','Seasonal offers, available while Autumn Harvest 2026 is active (September 1–December 1, UTC).',AD.autumnOffers.map(o=>[o.Name,Object.entries(o.Rewards).map(([id,n])=>`${fmt(n)} ${itemName(id)}`).join(', '),costsText(o.Costs)]));
for(const o of AD.autumnOffers)for(const [id,n] of Object.entries(o.Rewards))obtain(id,'Autumn Harvest Shop',`${o.Name}: ${fmt(n)} for ${costsText(o.Costs)}. Seasonal.`, 'autumn-shop');
for(const a of ARTICLES.filter(a=>a.quests))for(const q of a.quests)for(const r of q.rewards)obtain(r.item,a.title,`${q.title}: ${fmt(r.amount)}${q.season?' · '+q.season:q.type==='repeatable'?' · repeatable':''}`,a.id);
for(const [mobId,drops] of Object.entries(AD.mobDrops)){const a=existingId.get('mob-'+slug(mobId));if(!a)continue;const rows=[];for(const [kind,entries] of [['Guaranteed',drops.GuaranteedDrops],['Bonus',drops.BonusDrops]])for(const d of entries){const t=AD.tokens[d.TokenName];const count=d.Count||1;const quantity=d.HoneyMin?`${count} tokens × ${d.HoneyMin}–${d.HoneyMax} honey × mob level`:`${count*(d.Amount??t?.amount??1)}`;rows.push([t?itemCell(t.item):'Honey',quantity,kind,kind==='Guaranteed'?'100%':d.Chance+'%']);if(t)obtain(t.item,a.title,`${quantity}; ${kind==='Guaranteed'?'guaranteed drop':d.Chance+'% base bonus roll, subject to luck and drop limit'}.`,a.id)}tableFor(a,'Drop table',['Drop','Quantity','Type','Base roll chance'],rows,`Maximum ${drops.MaxDrops} physical tokens per defeat, including guaranteed tokens. Bonus rolls are checked in the listed order and skipped if no room remains. Loot Luck and mob level modify bonus chances, capped at 100%; these are roll chances, not final per-kill probabilities. Honey ranges scale with mob level.`);a.source+='; MobDropTables and MobRewardService';}
existingId.get('boss-runeboundcolossus').sections.push(['Rewards','No boss-specific item drop table was found in the checked encounter configuration. Rewards for magical quests are documented separately; they should not be treated as boss drops.']);
const ff=AD.fieldFind;
for(const f of WIKI_CATALOG.fields){const key=ff.FieldOverrides[f.id]?.DropTable||ff.LocationDropTables[f.location]||ff.DefaultDropTable;const rows=[];for(const d of ff.DropTables[key]){const t=AD.tokens[d.Token];if(!t)continue;const condition=`${d.Chance}% of successful field-find or leaf rewards${f.devLocked||f.location==='Testing'?' · development / testing field':''}.`;rows.push([itemCell(t.item),String(t.amount),d.Chance+'%']);obtain(t.item,f.name,condition,'field-'+slug(f.id))}tableFor(existingId.get('field-'+slug(f.id)),'Items found while gathering',['Item','Quantity','Share of finds'],rows,'A reward must first be triggered by gathering or breaking a field leaf. These percentages describe which reward is selected, not the chance per flower.');}
for(const [location,cfg] of Object.entries(AD.breakables.Locations)){for(const v of cfg.Variants||AD.breakables.Variants){const t=AD.tokens[v.Token];if(t)obtain(t.item,'Breakable '+(cfg.ResourceKind==='Mushroom'?'mushrooms':'pebbles'),`Break the ${readable(v.Template.replace('Pebble_',''))} variant in ${readable(location)}; quantity depends on its size.`,'gathering')}}
for(const d of AD.fireflies)obtain(d.ItemId,'Lantern fireflies','Possible reward from lantern fireflies at night; selected from a weighted reward pool.','gathering');
for(const d of AD.leafPool){const t=AD.tokens[d.Token];if(t)obtain(t.item,'Leaf Cutter',`Leaf Discovery: possible reward every 20th field attack (${d.Weight}% selection weight).`,'leaf-cutter')}
for(const d of AD.bags.BloomSatchel.Passive.DropTable.Entries){const t=AD.tokens[d.Token];if(t)obtain(t.item,'Bloom Satchel','Possible item drop from completing a passive bloom.','bloom-satchel')}
AD.levels.forEach((rewards,i)=>{for(const r of rewards)obtain(r.item,'Player level rewards',`Level ${i+1}: ${fmt(r.amount)}.`)});
obtain('FallingStar','Player level rewards','Levels above 10: 2 per level reward.');
for(const v of Object.values(AD.freePacks.Definitions))if(v.Kind==='Item')obtain(v.ItemId,v.DisplayName,`Claim ${v.Amount} once during the free-pack promotion, before October 1, 2026 (UTC).`);
obtain('MagicTicket_2','Magical quests','Complete a magical quest: 1–2 tickets per configured reward.','quest-guide');
obtain('egg_diamond','Map pickup','A one-time Diamond Egg pickup is placed in the current map.');
obtain('Pins','Map pickups','One-time pin pickups grant 3, 5, or 10 Pins per placement.');
for(const a of ARTICLES){if(a.obtaining?.length){a.sections=a.sections.filter(([h,p])=>!/^Obtaining/.test(h)&&!p.includes('World drop locations and rates have not yet been documented'));tableFor(a,'Obtaining',['Source','How to obtain'],a.obtaining,'Sources checked in Studio. Seasonal rewards require the event; development fields may be inaccessible in the published game.');a.source+='; acquisition configuration and reward handlers'}else if(a.category==='items'){a.sections=a.sections.filter(([h])=>!/^Obtaining/.test(h));a.sections.push(['Obtaining','No confirmed acquisition source was found in the checked configurations. This does not establish that the item is unobtainable.']);}a.related=[...new Set(a.related)].filter(id=>existingId.has(id)||CATEGORIES.some(c=>c[0]===id));}

