const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={home:'M3 10 12 3l9 7M5 9v12h5v-7h4v7h5V9',bees:'M12 3 20 7.5v9L12 21 4 16.5v-9Z M8 9h8M8 15h8',fields:'M4 20 19 5M5 15C1 6 11 3 21 3c0 10-3 20-12 16',npcs:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM4 21v-2a8 8 0 0 1 16 0v2',shops:'M3 9h18l-2-6H5ZM5 9v12h14V9M9 21v-7h6v7',items:'m12 3 9 5-9 5-9-5 9-5ZM3 8v9l9 5 9-5V8M12 13v9',mechanics:'M4 4h6v6H4ZM14 14h6v6h-6ZM14 4h6v6h-6ZM4 14h6v6H4Z',search:'M16 16 22 22M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z'};
const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.items}"/></svg>`;
const categoryName=id=>({tools:'Tools',bags:'Bags'}[id]||CATEGORIES.find(c=>c[0]===id)?.[1]||'Wiki');
const link=id=>{const a=ARTICLES.find(x=>x.id===id)||CATEGORIES.filter(c=>c[0]===id).map(c=>({id:c[0],title:c[1]}))[0];return a?`<a href="#${a.id}">${esc(a.title)}<span aria-hidden="true">↗</span></a>`:''};
const getId=()=>{try{return decodeURIComponent(location.hash.slice(1)||'home')}catch{return 'not-found'}};
const status=a=>a.verified?'Configuration checked':'Article in progress';
const imageFor=a=>a.image||CATEGORY_ART[a.category];
const number=n=>Number.isFinite(Number(n))?Number(n).toLocaleString('en-US'):'Not specified';
const assetPath=name=>'assets/'+(ASSET_FILES[name]||name);
const SEARCH_INDEX=ARTICLES.map(a=>({article:a,text:[a.title,a.type,a.summary,a.body,...(a.quests||[]).map(q=>q.title)].join(' ').toLowerCase()}));
$('#brand-name').textContent=WIKI_NAME.toUpperCase();
$('.sidebar-note small').textContent='THE '+WIKI_NAME.toUpperCase()+' WIKI';
$('footer').firstChild.textContent=WIKI_NAME+' Wiki · Player field guide ';

$('#navigation').innerHTML=CATEGORIES.map(([id,title])=>`<a href="#${id}" data-category="${id}">${icon(id)}<span>${title}</span></a>`).join('');
$('.search-wrap>span').innerHTML=icon('search');
function cards(articles){return `<div class="cards article-cards">${articles.map(a=>`<a class="card" href="#${a.id}">${a.image?`<div class="card-art"><img src="${assetPath(a.image)}" alt="" loading="lazy"></div>`:`<div class="card-icon">${icon(a.category)}</div>`}<div class="card-copy"><small>${esc(a.type)}</small><h3>${esc(a.title)}</h3><p>${esc(a.summary)}</p><span class="card-end">Read article <span aria-hidden="true">↗</span></span></div></a>`).join('')}</div>`}
function quests(a){return `<h2>${a.quests.length} quests</h2><p class="prose">Requirements and rewards from the current Studio configuration, checked 11 September 2026.</p><div class="quest-list">${a.quests.map((q,i)=>`<details class="quest" ${i===0?'open':''}><summary><span class="quest-number">${String(i+1).padStart(2,'0')}</span><span>${esc(q.title)}${q.season?`<small class="season-label">${esc(q.season)}</small>`:''}</span><span class="quest-toggle" aria-hidden="true">+</span></summary><div class="quest-body">${q.type==='repeatable'?'<p class="quest-kind">Repeatable quest</p>':''}<div><h3>Requirements</h3><ul>${q.requirements.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></div><div><h3>Rewards</h3><ul class="reward-list">${q.rewards.map(r=>`<li><strong>${number(r.amount)}</strong> ${esc(r.item==='honey'?'honey':r.item==='RoseQuartzChip'?'Rose Quartz Chip':r.item)}</li>`).join('')}</ul>${q.auraStacks?`<p>Trailkeeper Aura: +${number(q.auraStacks)} stacks</p>`:''}</div></div></details>`).join('')}</div>`}
function equipmentTables(){return `<h2>Tools</h2><p class="prose">Base values before player bonuses. Select a tool for its description and passive.</p><div class="table-wrap"><table><caption class="sr-only">Tool base statistics</caption><thead><tr><th scope="col">Tool</th><th scope="col">Rarity</th><th scope="col">Base price</th><th scope="col">Nectar / flower</th><th scope="col">Cooldown</th></tr></thead><tbody>${GAME_DATA.tools.map(t=>`<tr><th scope="row"><a href="#${slug(t.name)}">${esc(t.name)}</a></th><td>${t.rarity}</td><td>${number(t.price)}</td><td>${t.nectar}</td><td>${t.cooldown} s</td></tr>`).join('')}</tbody></table></div><h2>Bags</h2><div class="table-wrap"><table><caption class="sr-only">Bag base statistics</caption><thead><tr><th scope="col">Bag</th><th scope="col">Rarity</th><th scope="col">Base price</th><th scope="col">Capacity</th></tr></thead><tbody>${GAME_DATA.bags.map(b=>`<tr><th scope="row"><a href="#${slug(b.name)}">${esc(b.name)}</a></th><td>${b.rarity}</td><td>${number(b.price)}</td><td>${number(b.capacity)}</td></tr>`).join('')}</tbody></table></div>`}
function article(a){
 const tabNames=a.quests?[['overview','Overview'],['quests','Quests'],['dialogue','Dialogue'],['notes','Sources']]:[['overview','Overview'],['notes','Sources']];
 $('#main').innerHTML=`<div class="breadcrumb"><a href="#home">Home</a><span>/</span><a href="#${a.category}">${categoryName(a.category)}</a><span>/</span><span>${esc(a.title)}</span></div><div class="article-grid"><article><div class="eyebrow">${esc(a.type)} / ${esc(WIKI_NAME.toUpperCase())} FIELD GUIDE</div><h1>${esc(a.title)}</h1><div class="article-meta"><span class="badge ${a.verified?'checked':''}">${status(a)}</span>${a.verified?'<span>11 September 2026</span>':''}</div><p class="lead">${esc(a.summary)}</p><div class="tabs" role="tablist" aria-label="Article sections">${tabNames.map(([id,label],i)=>`<button id="tab-${id}" role="tab" aria-selected="${i===0}" tabindex="${i===0?0:-1}" aria-controls="article-content" data-tab="${id}">${label}</button>`).join('')}</div><div id="article-content" role="tabpanel" aria-labelledby="tab-overview" tabindex="0"></div></article><aside class="article-aside" aria-label="Article facts">${a.image?`<figure class="art"><img src="${assetPath(a.image)}" alt="${esc(a.imageLabel)}"><figcaption>${esc(a.imageLabel)}</figcaption></figure>`:''}<section class="panel"><h3>At a glance</h3><dl class="facts">${a.facts.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></section><section class="panel related"><h3>Connected pages</h3>${a.related.map(link).join('')}</section><p class="source">${a.verified?'Configuration checked in Studio. Values may change as Honeywild develops.':'This entry is being written. Undocumented details are not yet confirmed.'}</p></aside></div>`;
 const selectTab=key=>{
 document.querySelectorAll('[data-tab]').forEach(b=>{b.setAttribute('aria-selected',b.dataset.tab===key);b.tabIndex=b.dataset.tab===key?0:-1});$('#article-content').setAttribute('aria-labelledby',`tab-${key}`);
 let content='';
 if(key==='overview'){content=`<p class="prose">${esc(a.body).replace(/\n/g,'<br>')}</p>${a.quote?`<blockquote>“${esc(a.quote)}”<cite>— ${esc(a.title)}</cite></blockquote>`:''}${a.id==='equipment'?equipmentTables():a.sections.map(([h,p])=>`<h2>${esc(h)}</h2><p class="prose">${esc(p)}</p>`).join('')}${a.quests?`<button class="button-link" id="open-quests">Explore ${a.quests.length} quests →</button>`:''}`;}
 if(key==='quests')content=quests(a);
 if(key==='dialogue')content=`<h2>In Rocky’s words</h2><p class="prose">Open a quest to read its dialogue. Contains story spoilers.</p>${a.quests.map((q,i)=>`<details class="dialogue"><summary>${i+1}. ${esc(q.title)}</summary>${Object.entries(q.dialogue||{}).map(([phase,lines])=>`<h3>${esc(phase)}</h3>${lines.map(line=>`<p class="prose">“${esc(line)}”</p>`).join('')}`).join('')}</details>`).join('')}`;
 if(key==='notes')content=`<h2>Sources & accuracy</h2><p class="prose">${esc(a.source)}.</p><div class="note">${a.verified?'The listed data was read from the open Studio project on 11 September 2026. This is a configuration check, not confirmation that the published Roblox version has the same values.':'This article is based on saved design notes and project artwork. Some details are still being checked.'}</div><p class="prose">Honeywild is in development. If an in-game value differs, follow the game’s current display.</p>`;
 $('#article-content').innerHTML=content;
 document.querySelectorAll('.table-wrap,.quest-list').forEach(el=>{el.tabIndex=0;el.setAttribute('role','region');el.setAttribute('aria-label',el.classList.contains('quest-list')?'Scrollable quest list':'Scrollable equipment table')});
 if($('#open-quests'))$('#open-quests').onclick=()=>{selectTab('quests');$('#tab-quests').focus();$('#tab-quests').scrollIntoView({block:'nearest'})};
 };
 document.querySelectorAll('[data-tab]').forEach(b=>{b.onclick=()=>selectTab(b.dataset.tab);b.onkeydown=e=>{const tabs=[...document.querySelectorAll('[data-tab]')];let n=tabs.indexOf(b);if(e.key==='ArrowRight')n=(n+1)%tabs.length;else if(e.key==='ArrowLeft')n=(n+tabs.length-1)%tabs.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=tabs.length-1;else return;e.preventDefault();tabs[n].focus();selectTab(tabs[n].dataset.tab)}});selectTab('overview');
}

function mountDirectory(list){let page=0;const size=24;function update(){const q=$('#directory-filter').value.trim().toLowerCase();const filtered=list.filter(a=>[a.title,a.type,a.rarity,a.color,a.summary].join(' ').toLowerCase().includes(q));const pages=Math.max(1,Math.ceil(filtered.length/size));page=Math.min(page,pages-1);$('#directory-results').innerHTML=filtered.length?cards(filtered.slice(page*size,(page+1)*size)):'<p class="prose">No matching articles in this category.</p>';$('#directory-count').textContent=filtered.length+' articles';$('#page-number').textContent='Page '+(page+1)+' of '+pages;$('#page-prev').disabled=page===0;$('#page-next').disabled=page>=pages-1;}$('#directory-filter').oninput=()=>{page=0;update()};for(const [id,delta] of [['page-prev',-1],['page-next',1]])$('#'+id).onclick=()=>{page+=delta;update();$('#directory-results').scrollIntoView({block:'start'})};update();}

function render(){
 const id=getId(),a=ARTICLES.find(a=>a.id===id),category=a?.category||(['tools','bags'].includes(id)?'shops':id);
 document.querySelectorAll('nav a').forEach(el=>{const active=el.dataset.category===category;el.classList.toggle('active',active);if(active)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')});
 document.body.classList.remove('nav-open');$('#menu').setAttribute('aria-expanded','false');$('#results').hidden=true;$('#search').value='';
 if(a){document.title=`${a.title} · ${WIKI_NAME} Wiki`;article(a)}
 else if(id==='home'){
 document.title=`${WIKI_NAME} Wiki`;
 $('#main').innerHTML=`<section class="home-welcome"><h1>Welcome to the ${esc(WIKI_NAME)} Wiki!</h1><div class="home-wordmark" aria-hidden="true"><img src="${assetPath('gathering.png')}" alt=""><span>${esc(WIKI_NAME)}</span><small>A little hive. A world to explore.</small></div><p>A guide to ${esc(WIKI_NAME)}, a Roblox bee-collecting adventure. Find information about bees, quests, equipment, items, and the world around your hive.</p><p class="welcome-note">The game is growing, and so is this wiki.</p></section><section class="wiki-directory"><h2>Wiki Articles</h2><div class="icon-grid">${[
 ['bees','Bees','bee-egg-icon.png'],['fields','Fields','field-icon.png'],['npcs','NPCs','rocky.png'],['quest-guide','Quests','quests.png'],['items','Items','rose-quartz.png'],
 ['shops','Shops','shop.png'],['tools','Tools','honey-dipper.png'],['bags','Bags','bags.png'],['mechanics','Mechanics','gear.png'],['gathering','Gathering','gathering.png'],['mobs','Mobs & Bosses','gear.png'],['abilities','Tokens & Abilities','rose-quartz.png']
 ].map(([id,label,img])=>`<a class="icon-entry" href="#${id}"><img src="${assetPath(img)}" alt="" width="112" height="112"><span>${label}</span></a>`).join('')}</div></section><section class="similar-pages" aria-label="Useful pages"><h2>Useful pages</h2><div><a href="#quest-guide">Quest guide</a><a href="#equipment">Equipment comparison</a><a href="#rocky">Rocky</a><a href="#gathering">Gathering</a></div></section>`;
 }else if(CATEGORIES.some(c=>c[0]===id)||['tools','bags'].includes(id)){
 document.title=`${categoryName(id)} · ${WIKI_NAME} Wiki`;
 const list=ARTICLES.filter(a=>id==='tools'?a.type==='Tool':id==='bags'?a.type==='Bag':a.category===id);
 $('#main').innerHTML=`<div class="breadcrumb"><a href="#home">Home</a><span>/</span><span>${categoryName(id)}</span></div><div class="directory-heading"><div><div class="eyebrow">EXPLORE / ${list.length} ARTICLES</div><h1>${categoryName(id)}</h1><p class="lead">${CATEGORY_COPY[id]||(id==='tools'?'Compare gathering patterns, base stats, and tool passives.':'Find the right capacity for your next field trip.')}</p></div>${icon(id)}</div><div class="directory-controls"><label for="directory-filter">Filter articles<input id="directory-filter" type="search" maxlength="100" placeholder="Name, rarity, or color…"></label><span id="directory-count" role="status"></span></div><div id="directory-results"></div><nav class="pagination" aria-label="Article pages"><button id="page-prev">Previous</button><span id="page-number"></span><button id="page-next">Next</button></nav>`;
 mountDirectory(list);
 }else{document.title=`Page not found · ${WIKI_NAME}`;$('#main').innerHTML='<div class="eyebrow">UNEXPLORED TERRITORY</div><h1>Page not found.</h1><p class="lead">This entry is not in the field guide yet.</p><a class="button-link" href="#home">Back to the field guide</a>'}
 window.scrollTo(0,0);
}
$('#search').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();if(!q){$('#results').hidden=true;return}const matches=SEARCH_INDEX.filter(row=>row.text.includes(q)).map(row=>row.article);$('#results').innerHTML=matches.length?`<div class="search-count">${matches.length} articles found${matches.length>12?' · showing the first 12; refine your search':''}</div>`+matches.slice(0,12).map(a=>`<a href="#${a.id}"><span>${esc(a.title)}</span><small>${categoryName(a.category)}</small></a>`).join(''):'<p>No articles found. Try a bee, item, or NPC name.</p>';$('#results').hidden=false});
$('#search').addEventListener('keydown',e=>{if(e.key==='Escape')$('#results').hidden=true;if(e.key==='Enter'&&!$('#results').hidden){const a=$('#results a');if(a){a.click();$('#search').blur()}}if(e.key==='ArrowDown'&&!$('#results').hidden){e.preventDefault();$('#results a')?.focus()}});
$('#results').addEventListener('keydown',e=>{const links=[...document.querySelectorAll('#results a')],n=links.indexOf(document.activeElement);if(e.key==='ArrowDown'){e.preventDefault();links[(n+1)%links.length]?.focus()}if(e.key==='ArrowUp'){e.preventDefault();if(n===0)$('#search').focus();else links[n-1]?.focus()}if(e.key==='Escape'){$('#results').hidden=true;$('#search').focus()}});
$('#results').addEventListener('click',e=>{if(e.target.closest('a')){$('#results').hidden=true;$('#search').value=''}});
$('#menu').onclick=()=>{const open=document.body.classList.toggle('nav-open');$('#menu').setAttribute('aria-expanded',open)};
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus()}if(e.key==='Escape'){$('#results').hidden=true;document.body.classList.remove('nav-open');$('#menu').setAttribute('aria-expanded','false')}});
document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))$('#results').hidden=true});
window.addEventListener('hashchange',()=>{render();$('#main').focus({preventScroll:true})});render();



// Keep the mobile drawer out of keyboard navigation when closed.
const mobileSidebar=window.matchMedia('(max-width: 820px)');
function syncSidebar(){const open=document.body.classList.contains('nav-open');$('#sidebar').inert=mobileSidebar.matches&&!open;$('#sidebar').setAttribute('aria-hidden',String(mobileSidebar.matches&&!open));$('#drawer-backdrop').hidden=!mobileSidebar.matches||!open;}
new MutationObserver(syncSidebar).observe(document.body,{attributes:true,attributeFilter:['class']});
mobileSidebar.addEventListener('change',syncSidebar);
$('#drawer-backdrop').onclick=()=>{document.body.classList.remove('nav-open');$('#menu').setAttribute('aria-expanded','false');$('#menu').focus()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&mobileSidebar.matches)$('#menu').focus();if(e.key==='Tab'&&mobileSidebar.matches&&document.body.classList.contains('nav-open')){const focusable=[$('#menu'),...[...$('#sidebar').querySelectorAll('a,button')].filter(el=>el.getClientRects().length)];const index=focusable.indexOf(document.activeElement);e.preventDefault();const next=(index+(e.shiftKey?-1:1)+focusable.length)%focusable.length;focusable[next].focus()}});
syncSidebar();

