// Build wiki articles from a reviewed, public-facing configuration snapshot.
const catalogText=s=>String(s??'').replace(/<[^>]*>/g,'').trim();
const readable=s=>String(s??'').replace(/([a-z0-9])([A-Z])/g,'$1 $2').replace(/_/g,' ');
const sourceLabel=name=>name+' · Studio configuration checked September 11, 2026';
const existingId=new Map(ARTICLES.map(a=>[a.id,a]));
function addEntry(a){a.verified=true;a.sections??=[];a.related??=[];a.facts??=[];a.body??=a.summary;a.source??=sourceLabel('Game configuration');if(existingId.has(a.id)){Object.assign(existingId.get(a.id),a)}else{ARTICLES.push(a);existingId.set(a.id,a)}}
CATEGORIES.find(c=>c[0]==='npcs')[1]='Bears & NPCs';
CATEGORIES.push(['mobs','Mobs & Bosses',''],['abilities','Tokens & Abilities','']);
CATEGORY_COPY.mobs='Explore configured creatures, combat stats, and the Runebound Colossus.';
CATEGORY_COPY.abilities='Read the ability descriptions used by the current bee roster.';
const itemIds=new Map(WIKI_CATALOG.items.map(v=>[v.id,({'Pebble':'pebbles','RoseQuartzChip':'rose-quartz-chip','Mossy Pebble':'mossy-pebble'}[v.id]||'item-'+slug(v.id))]));
for(const t of WIKI_CATALOG.abilities)addEntry({id:'ability-'+slug(t.id),title:t.name||readable(t.id.replace(/Token$/,'')),category:'abilities',type:'Ability token',summary:catalogText(t.description)||'A configured bee ability token.',facts:[['Token',readable(t.id)]],source:sourceLabel('Bee ability token catalog')});
for(const b of WIKI_CATALOG.bees){const abilities=b.AbilityIds.map(id=>WIKI_CATALOG.abilities.find(t=>t.id===id)).filter(Boolean);addEntry({id:slug(b.DisplayName),title:b.DisplayName,category:'bees',type:'Bee',summary:catalogText(b.Description).split('\n')[0],body:catalogText(b.Description),rarity:b.Rarity,color:b.Color,facts:[['Rarity',b.Rarity],['Color',b.Color],['Attack damage',b.AttackDamage],['Gather amount',b.GatherAmount],['Gather speed',b.GatherSpeed],['Convert amount',b.ConvertAmount],['Convert speed',b.ConvertSpeed],['Move speed',b.MoveSpeed],['Required net tier',b.RequiredNetTier],['Favorite food',b.FavoriteFoodId||'Not specified']],sections:[['Base statistics','The listed values are the bee definition’s base values. Levels, ascension, food, tags, and active effects can change the result in game.'],...abilities.map(t=>[t.name||readable(t.id),catalogText(t.description)||'The configured ability does not include a player-facing description.']),['Traits',(b.Tags||[]).map(readable).join(', ')],...(b.StandardRollable===false?[['Obtaining','This bee is excluded from standard rolls. Use its dedicated acquisition method described in the game.']]:[])],related:abilities.map(t=>'ability-'+slug(t.id)).concat(itemIds.get(b.FavoriteFoodId)||'gathering'),source:sourceLabel('BeeData and ability definitions')})}
const npcId=n=>n.Id==='Rocky'?'rocky':slug(n.DisplayName);
const npcs=[...WIKI_CATALOG.npcs,...WIKI_CATALOG.serviceNpcs.map(n=>({Id:n.service,DisplayName:n.service,NpcTag:n.id,Description:'A '+n.service.toLowerCase()+' NPC present in the game world.',Location:n.location||'Not documented',quests:[]}))];
for(const n of npcs){const seasonal=WIKI_CATALOG.seasonal.filter(q=>q.npcTag.replace(/^Autumn2026_/, '')===n.NpcTag);const all=[...n.quests,...seasonal];addEntry({id:npcId(n),title:n.DisplayName,category:'npcs',type:n.DisplayName.includes('Bear')?'Bear / quest giver':'NPC / quest giver',summary:n.Description,body:n.Description+' '+(n.quests.length?`The current definition contains ${n.quests.length} regular quests.`:'No regular questline was found in the default quest catalog.')+(seasonal.length?` There are also ${seasonal.length} configured Autumn Harvest quests.`:''),facts:[['Location',readable(n.Location)],['Regular quests',n.quests.length],['Seasonal quests',seasonal.length]],quests:all,quote:all[0]?.dialogue?.Claim?.[0],sections:[['Quest types','Regular and repeatable quests are listed first. Seasonal entries are labeled Autumn Harvest 2026 and are available only when the corresponding event is active.']],related:['quest-guide','items'],source:sourceLabel('NPC index, world NPC anchors, and regular / Autumn Harvest quest catalogs')})}
for(const v of WIKI_CATALOG.items){const id=itemIds.get(v.id);const prior=existingId.get(id);const title=v.name||readable(v.id);const description=catalogText(v.description);const bee=WIKI_CATALOG.bees.find(b=>b.Id===v.BeeType);const sections=[];if(v.exp!==undefined)sections.push(['Feeding',`Configured feeding experience: ${v.exp}.`]);if(v.maxEnergyGain!==undefined)sections.push(['Energy',`Configured maximum-energy gain: ${v.maxEnergyGain}.`]);if(prior)sections.push(...prior.sections);if(!description&&!prior)sections.push(['Obtaining & use','This item is defined in the game catalog. Its sources, prices, and uses have not yet been documented here.']);addEntry({id,title,category:'items',type:readable(v.category),rarity:v.rarity,image:ITEM_ART[v.id]||prior?.image,imageLabel:title+' item artwork',summary:description||prior?.summary||`${title} is a ${readable(v.category).toLowerCase()} item in the current catalog.`,body:description||prior?.body||`${title} is listed in the game’s item catalog with ${v.rarity||'unspecified'} rarity.`,facts:[['Category',readable(v.category)],['Rarity',v.rarity||'Not specified']],sections,related:bee?[slug(bee.DisplayName)]:prior?.related||[],source:sourceLabel('ItemData and generated bee egg / jelly definitions')})}
for(const v of [...WIKI_CATALOG.hats,...WIKI_CATALOG.gear]){const isHat=WIKI_CATALOG.hats.includes(v);addEntry({id:slug(v.DisplayName),title:v.DisplayName,category:'shops',type:isHat?'Hat':'Gear',summary:v.Description,rarity:v.Rarity,facts:[['Rarity',v.Rarity],['Base price',fmt(v.Price)],['Slot',v.EquipmentSlot||(isHat?'Hat':'Equipment')],...(v.ShopVisible===false?[['Shop visibility','Hidden in configuration']]:[])],sections:[['Stat modifiers',(v.Stats||[]).map(s=>`${s.DisplayName}: ${s.Mode==='Mult'?'×':s.Mode==='Add'?'+':''}${s.Value} (${s.Mode}).`).join(' ')],...(v.ItemCosts?[['Material cost',Object.entries(v.ItemCosts).map(([id,n])=>`${n} ${readable(id)}`).join(', ')]]:[]),...(v.Passive?[['Passive: '+v.Passive.DisplayName,v.Passive.Description]]:[])],related:['equipment',...Object.keys(v.ItemCosts||{}).map(id=>itemIds.get(id)).filter(Boolean)],source:sourceLabel(isHat?'HatConfig':'GearData')})}
for(const f of WIKI_CATALOG.fields){const relevant=npcs.filter(n=>[...n.quests,...WIKI_CATALOG.seasonal.filter(q=>q.npcTag.replace(/^Autumn2026_/, '')===n.NpcTag)].some(q=>q.requirements.some(r=>r.replace(/\s/g,'').toLowerCase().includes(f.id.toLowerCase()))));addEntry({id:'field-'+slug(f.id),title:f.name,category:'fields',type:'Field',summary:`${f.name} is a gathering field${f.location?' in '+readable(f.location):''}.`,facts:[['Region',readable(f.location||'Not specified')],['Development lock',f.devLocked?'Locked in current Studio configuration':'Not flagged']],sections:[['Availability','This entry comes from the field objects in the open Studio map. Development locks and testing regions can differ from the published game.'],['Related quests',relevant.length?relevant.map(n=>n.DisplayName).join(', ')+' have quest objectives involving this field.':'No matching NPC objectives were found in the exported quest descriptions.']],related:relevant.map(npcId).concat('gathering'),source:sourceLabel('World field metadata')})}
for(const m of WIKI_CATALOG.mobs)addEntry({id:'mob-'+slug(m.id),title:m.DisplayName,category:'mobs',type:'Mob',summary:`${m.DisplayName} is a ${m.Tags.map(readable).join(', ').toLowerCase()} enemy associated with ${readable(m.FieldName)}.`,facts:[['Field',readable(m.FieldName)],['Base health',m.MaxHealth],['Configured level',m.LevelMin?m.LevelMin+'–'+m.LevelMax:m.Level],['Base contact damage',m.ContactDamage],['Respawn',m.RespawnSeconds+' seconds']],sections:[['Combat values','These are base configuration values. Level scaling and other combat modifiers may change health and damage.']],related:['field-'+slug(m.FieldName)],source:sourceLabel('MobDefinitions')});
for(const b of WIKI_CATALOG.bosses)addEntry({id:'boss-'+slug(b.id),title:b.name,category:'mobs',type:'Boss',summary:`${b.name} is a configured magical boss encounter.`,facts:[['Default difficulty',b.difficulty],['Encounter duration',b.duration+' seconds']],sections:b.phases.map(p=>[p.name,`${catalogText(p.description)}. Phase threshold: ${Math.round(p.health*100)}% health.`]),related:[],source:sourceLabel('MagicalBossCatalog')});
CATEGORY_COPY.bees=`All ${WIKI_CATALOG.bees.length} configured bees, with base stats, traits, favorite foods, and abilities.`;
CATEGORY_COPY.npcs=`All ${npcs.length} indexed or placed NPCs, including the bears, with regular and seasonal quests.`;
CATEGORY_COPY.items=`All ${WIKI_CATALOG.items.length} item definitions, including bee eggs and jellies. Some configured items may be placeholders or unavailable.`;
// Validate the identifiers and asset paths used inside links and image attributes.
const validId=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const ids=new Set();
for(const a of ARTICLES){if(!validId.test(a.id)||ids.has(a.id))throw new Error('Invalid or duplicate article ID: '+a.id);ids.add(a.id);if(a.image&&!/^(?:[a-z0-9_-]+\/)*[a-z0-9_-]+\.(?:png|webp)$/.test(a.image))throw new Error('Invalid local asset path');}
for(const a of ARTICLES)a.related=[...new Set(a.related)].filter(id=>ids.has(id)||CATEGORIES.some(c=>c[0]===id));

