const WIKI_NAME = 'Honeywild';
const CATEGORIES = [
 ['home','Overview','⌂'],['bees','Bees','⬡'],['fields','Fields','❧'],['npcs','NPCs & Quests','♙'],['shops','Shops & Gear','▥'],['items','Items','◇'],['mechanics','Mechanics','⚙']
];
const ARTICLES = [
 {id:'rocky',category:'npcs',title:'Rocky',type:'Quest giver',image:'rocky.png',imageLabel:'Existing Rocky model preview',summary:'A quiet face in the stone. Help Rocky rediscover motion, memory, and a little hope.',body:'Rocky begins as a stone creature with a small, changing face. His questline is built around the rocky fields, pebbles, and gradual changes to his appearance. The story is about bringing life back to someone who has been still for a very long time.',facts:[['Role','Quest giver'],['Area','Rocky location'],['Theme','Stone & recovery'],['Content','Draft from project notes']],related:['pebbles','rocky-fields','quest-guide'],source:'RockyQuestMemory.md and RockyQuestline15FullDraft.md',sections:[['Finding Rocky','Explore the Rocky location. A precise map marker and access requirements still need to be checked in the current game.'],['A story told through stone','The saved design links new forms to quest milestones. Mossy is the first major transformation; later forms explore different stages of Rocky’s story.']],quests:['A Very Still Hello','Quartz Does Not Blink','Something Moves In Granite','Amber And Quartz Disagree','Moss Learns The Edges']},
 {id:'charm-bee',category:'bees',title:'Charm Bee',type:'Bee',image:'charm-egg.png',imageLabel:'Charm Bee egg artwork',summary:'Meet Charm Bee and explore its related artwork.',body:'Charm Bee appears in the project’s bee work and has dedicated face, body, egg, and jelly artwork. This starter article uses its existing egg icon. Rarity, gathering stats, and ability details are awaiting a current configuration check.',facts:[['Entry','Charm Bee'],['Artwork','Egg icon'],['Stats','Not verified']],related:['gathering'],source:'Project bee tasks and deliverables/charm-bee-assets',sections:[['Abilities & stats','Verified ability descriptions, cooldowns, and base stats will be added from the current bee configuration.']]},
 {id:'rocky-fields',category:'fields',title:'Rocky fields',type:'Area guide',summary:'Amber, quartz, and granite form the setting for Rocky’s early quests.',body:'The saved quest draft names AmberMine, QuartzQuarry, and GraniteMine as early gathering destinations. Some names also have internal aliases in the notes. This page uses the draft names until the live display names are checked.',facts:[['Region','Rocky location'],['Draft fields','3'],['Access','Not verified']],related:['rocky','pebbles'],source:'RockyQuestline15FullDraft.md',sections:[['AmberMine','An early destination in Rocky’s first quest.'],['QuartzQuarry','The second quest introduces a comparison between quartz and amber.'],['GraniteMine','The third quest brings the player into the granite part of the location.']]},
 {id:'equipment',category:'shops',title:'Equipment guide',type:'Starter article',summary:'Tools, bags, and hats: a place to compare your next upgrade.',body:'The project has separate tool, bag, and hat systems. This guide is ready for the shop inventory and prices to be checked and added. No purchase values are assumed in this preview.',facts:[['Equipment','Tools, bags, hats'],['Prices','Not verified']],related:['gathering'],source:'Items and Tools project tasks',sections:[['What to compare','For each item, document its shop, requirements, cost, base stats, and any passive ability. Link every material requirement to its own item page.']]},
 {id:'pebbles',category:'items',title:'Pebbles',type:'Resource guide',image:'pebble.png',imageLabel:'Cracked Pebble artwork · related item',summary:'Small stones with a role in Rocky’s developing questline.',body:'Pebble objectives appear from the second quest in the saved Rocky draft. The project also contains artwork for related stone items, including Cracked Pebble, shown here. The exact sources, rates, and exchange uses need a current game check.',facts:[['Connected NPC','Rocky'],['Family','Stone resources'],['Drop rates','Not verified']],related:['rocky','rocky-fields'],source:'RockyQuestMemory.md, RockyQuestline15FullDraft.md and existing item artwork',sections:[['Obtaining','Current collection sources need verification. Older notes mention changes to ground pickups, so those notes alone should not be used as a live farming guide.']]},
 {id:'quest-guide',category:'mechanics',title:'Quest guide',type:'Mechanic',summary:'Follow objectives, collect rewards, and uncover an NPC’s story.',body:'The saved quest system supports objectives such as gathering nectar, collecting items or tokens, and reaching progression milestones. Each NPC article will list its own quest sequence and rewards.',facts:[['System','NPC progression'],['Example NPC','Rocky']],related:['rocky','gathering'],source:'RockyQuestMemory.md',sections:[['Reading an objective','Pay attention to whether an objective asks you to collect something during the quest or own an amount in your inventory. These are different conditions.'],['Milestones','Some quest completions are designed to unlock more than currency. Rocky’s planned changes in appearance are one example.']]},
 {id:'gathering',category:'mechanics',title:'Gathering & conversion',type:'Mechanic',summary:'The core loop: gather in fields and return to your hive to convert.',body:'The game’s existing work includes flower gathering, bees, inventory capacity, and hive conversion. This article establishes the structure for a beginner guide; exact controls and rates need to be checked in the current game.',facts:[['Loop','Fields → hive'],['Rates','Not verified']],related:['charm-bee','equipment','rocky-fields'],source:'Fields, Items and bee project tasks',sections:[['Gathering','Field and bee articles will explain where resources come from and how equipment changes gathering.'],['Conversion','The hive is part of the conversion loop. Verified timings, ratios, and upgrades can be added here.']]}
];

const CATEGORY_COPY={bees:'Meet your companions and learn what makes each bee different.',fields:'Find gathering destinations and the quests that bring you there.',npcs:'Meet the locals. Follow their quests, rewards, and stories.',shops:'Compare gathering tools and bags before your next upgrade.',items:'Learn where resources come from and what they are used for.',mechanics:'Understand gathering, conversion, and progression.'};
const CATEGORY_ART={bees:'charm-egg.png',fields:'flower.png',npcs:'rocky.png',items:'pebble-exact.png'};
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,'');
const clean=s=>s.replace(/<[^>]*>/g,'');
const fmt=n=>Number(n).toLocaleString('en-US');
const rocky=ARTICLES.find(a=>a.id==='rocky');
Object.assign(rocky,{verified:true,source:'Rocky quest definitions · Studio configuration checked September 11, 2026',quests:GAME_DATA.quests,quote:GAME_DATA.quests[0].dialogue.Claim[0],facts:[['Role','Quest giver'],['Area','Rocky location'],['Configured quests','5'],['Checked','11 Sep 2026']],sections:[['His first chapter','Rocky’s five configured quests take you through AmberField, QuartzQuarry, and GraniteMine. Later objectives include a Berry Mite, Pebbles, and AmberField Achievement II.'],['A character who changes','Rocky’s story is about stone slowly regaining warmth and identity. The quest dialogue hints at changes to his face and the arrival of moss. Future forms described in design notes are not included in this current quest list.']]});
const equipment=ARTICLES.find(a=>a.id==='equipment');
Object.assign(equipment,{verified:true,type:'Equipment comparison',summary:'Compare five tools and four bags using their configured base values.',body:'Choose a tool for its gathering pattern, cooldown, and passive. Choose a bag for its capacity. The tables show base configuration values before player bonuses.',facts:[['Tools','5'],['Bags','4'],['Checked','11 Sep 2026']],source:'ToolConfig and BagsConfig · Studio configuration checked September 11, 2026',sections:[]});
const pebbles=ARTICLES.find(a=>a.id==='pebbles');
Object.assign(pebbles,{verified:true,image:'pebble-exact.png',imageLabel:'Pebble item artwork',summary:'A stone resource collected and handed over during Rocky’s quests.',body:'Rocky rewards one Pebble for his first quest and two for his second. The second quest asks for a freshly collected Pebble; the fourth asks you to obtain ten and give them to Rocky.',facts:[['Type','Resource'],['NPC','Rocky'],['Quest 4 hand-in','10 Pebbles']],source:'Rocky quest definitions · Studio configuration checked September 11, 2026',sections:[['Collecting versus owning','Quartz Does Not Blink asks you to collect a Pebble after accepting the quest. Pebbles already in your inventory do not satisfy that freshly collected objective.'],['Quest rewards','A Very Still Hello rewards 1 Pebble. Quartz Does Not Blink rewards 2 Pebbles. World drop locations and rates have not yet been documented.']]});
const fields=ARTICLES.find(a=>a.id==='rocky-fields');Object.assign(fields,{image:'flower.png',imageLabel:'Flower artwork · region guide',summary:'AmberField, QuartzQuarry, and GraniteMine are destinations in Rocky’s first chapter.',body:'These three field identifiers appear in Rocky’s current quest requirements. Use the quest list to see the amounts and colors required. Map locations and access requirements are still being documented.',sections:[['AmberField','Rocky’s first quest requires 8,000 nectar from AmberField and 5,000 red nectar.'],['QuartzQuarry','The second quest requires 18,000 nectar from QuartzQuarry.'],['GraniteMine','The third quest requires 14,000 nectar from GraniteMine.']],source:'Rocky quest definitions · Studio configuration checked September 11, 2026'});
for(const t of GAME_DATA.tools){ARTICLES.push({id:slug(t.name),category:'shops',type:'Tool',title:t.name,verified:true,summary:clean(t.description).split('\n')[0],body:clean(t.description),facts:[['Rarity',t.rarity],['Base price',fmt(t.price)],['Nectar per flower',fmt(t.nectar)],['Cooldown',t.cooldown+' s']],related:['equipment','gathering'],source:'ToolConfig · Studio configuration checked September 11, 2026',sections:[['Base stats','These values are from the current tool configuration. Player bonuses and active effects can change the result of a scoop.']]})}
for(const b of GAME_DATA.bags){ARTICLES.push({id:slug(b.name),category:'shops',type:'Bag',title:b.name,verified:true,summary:b.description,body:b.description,facts:[['Rarity',b.rarity],['Base price',fmt(b.price)],['Base capacity',fmt(b.capacity)]],related:['equipment','gathering'],source:'BagsConfig · Studio configuration checked September 11, 2026',sections:[['Capacity','The listed capacity is the base value before bonuses.']]})}
ARTICLES.push({id:'rose-quartz-chip',category:'items',title:'Rose Quartz Chip',type:'Quest reward',image:'rose-quartz.png',imageLabel:'Rose Quartz Chip item artwork',verified:true,summary:'A reward from Rocky’s fourth quest.',body:'Amber And Quartz Disagree rewards one Rose Quartz Chip along with 30,000 honey.',facts:[['Source','Rocky · quest 4'],['Amount','1']],related:['rocky','pebbles'],source:'Rocky quest definitions · Studio configuration checked September 11, 2026',sections:[]});
ARTICLES.push({id:'mossy-pebble',category:'items',title:'Mossy Pebble',type:'Quest reward',image:'mossy-pebble.png',imageLabel:'Mossy Pebble item artwork',verified:true,summary:'A moss-covered reward at the end of Rocky’s first chapter.',body:'Moss Learns The Edges rewards two Mossy Pebbles along with 120,000 honey.',facts:[['Source','Rocky · quest 5'],['Amount','2']],related:['rocky','pebbles'],source:'Rocky quest definitions · Studio configuration checked September 11, 2026',sections:[]});
