const guideLink=id=>({id,text:ARTICLES.find(a=>a.id===id)?.title||id});
const publicItem=id=>ARTICLES.find(a=>a.id===itemIds.get(id));
const publicFood=Object.entries(REFERENCE_DATA.foods).filter(([id])=>publicItem(id));
function referenceArticle(a){addEntry({category:'mechanics',type:'Reference guide',facts:[],sections:[],related:[],...a});return existingId.get(a.id)}
const foodGuide=referenceArticle({id:'feeding-and-energy',title:'Food, energy & rest',summary:'Compare food effects, restore tired bees, and understand the permanent energy bonus.',image:'webp/items/treat.webp',imageLabel:'Treat item artwork',facts:[['Ordinary food','10 XP + 1 energy each'],['Energy food cap','+15 per bee'],['Default energy rest','20 seconds']],sections:[['XP food and energy food','Ordinary foods in this guide grant 10 XP and restore 1 current energy per item, up to the bee’s maximum. Voltberry and Honeyheart Wafer instead add 1 permanent maximum energy each and grant no XP or immediate energy refill.'],['The +15 energy cap','The permanent food bonus is shared between Voltberries and Honeyheart Wafers. A bee can gain at most +15 maximum energy from these foods combined. The game limits consumption to the remaining useful amount; feeding more at the cap is rejected.'],['Energy rest and deep rest','When energy runs out, a bee rests to refill it. The default energy rest is 20 seconds. When its separate action reserve is exhausted, deep rest takes 30 base seconds and refills both actions and energy.'],['Resting at the hive','Hive rest multiplies rest speed by 1.25. With no other rest-speed bonus, that means 16 seconds for a default energy rest or 24 seconds for deep rest. Bee Rest Speed bonuses can shorten these times further.']],related:['favorite-foods','bees','leafy-belt','autumn-shop'],source:sourceLabel('ItemData, InventoryManager feeding handler, BeeService and BeeResourceService')});
tableFor(foodGuide,'Food effects',['Food','Base XP','Current energy','Permanent max energy'],publicFood.map(([id,d])=>[itemCell(id),d.xp,d.energy??1,d.maxEnergy?'+'+d.maxEnergy:'—']),'Energy restoration stops at the bee’s current maximum. Permanent energy foods share a +15 bonus cap.');
const favorites=referenceArticle({id:'favorite-foods',title:'Favorite foods & ascension',summary:'Find each bee’s favorite food and compare the chance of ascension from feeding.',facts:[['Roll condition','Matching favorite food'],['Batch rule','Independent rolls'],['Already ascended','No extra ascension roll']],sections:[['When favorite food matters','A non-ascended bee gets an ascension chance when it consumes its own favorite food. Other foods still give their usual feeding effects, but they do not trigger this favorite-food ascension roll.'],['How batches work','Feeding a batch uses the same probability as one independent roll per consumed item: 1 − (1 − 1/N)ⁿ, where N is the rarity’s one-in value and n is the amount eaten. A one-in value is not a guarantee or a pity counter.'],['Reading the odds','For a Regular bee, one matching food gives a 1 in 5,000 chance. Feeding 5,000 gives about a 63.22% chance of at least one success, not 100%. No favorite-food roll applies to Special bees or bees that are already ascended.']],related:['feeding-and-energy','bees'],source:sourceLabel('BeeData, BeeFeedingConfig and InventoryManager')});
tableFor(favorites,'Ascension chances',['Bee rarity','One matching food','Chance'],Object.entries(REFERENCE_DATA.ascensionOneIn).map(([r,n])=>[r,'1 in '+fmt(n),(100/n)+'%']));
tableFor(favorites,'Favorite food directory',['Bee','Rarity','Favorite food'],AVAILABLE_BEES.map(b=>[guideLink(slug(b.DisplayName)),b.Rarity,itemCell(b.FavoriteFoodId)]));
const lootGuide=referenceArticle({id:'loot-guide',title:'Drops & gathering rewards',summary:'Understand guaranteed drops, bonus rolls, field finds, and equipment reward pools.',image:'webp/equipment/mob-berrymite.webp',imageLabel:'Berry Mite model preview',facts:[['Mob drop tables','3'],['Field finds','Conditional rewards']],sections:[['Guaranteed drops come first','Guaranteed mob tokens use up part of the drop limit before bonus rolls are processed. A token can represent more than one item: token count and item quantity are separate values.'],['Why a bonus percentage is not a per-kill rate','Bonus entries are checked in their listed order. If earlier drops fill the physical-token limit, later entries are skipped. Loot Luck and mob level also modify the roll. Treat a listed bonus chance as a base roll value, not a guaranteed share of kills.'],['Honey scales with mob level','The minimum and maximum honey listed in mob drop tables are multiplied by the mob’s level. Base contact damage and health are reference values; combat scaling can change the encounter.'],['Field finds and breakables','Gathering must first trigger a find before the field’s reward table chooses an item. A 10% share of finds does not mean a 10% chance per flower. Breakable pebbles and mushrooms use their own variants and size-dependent quantities.'],['Equipment can create extra rewards','Leaf Cutter’s Leaf Discovery checks every 20th field attack. Bloom Satchel can create item drops when its bloom passive completes. Their item pages list the confirmed reward sources.']],related:['mob-berrymite','mob-graniteroller','mob-quartzspitter','leaf-cutter','bloom-satchel','field-guide'],source:sourceLabel('MobDropTables, MobRewardService, FieldFindConfig, breakables and equipment passives')});
tableFor(lootGuide,'Mob reference',['Mob','Field','Base health','Base contact damage','Respawn'],WIKI_CATALOG.mobs.map(m=>[guideLink('mob-'+slug(m.id)),guideLink('field-'+slug(m.FieldName)),fmt(m.MaxHealth),m.ContactDamage,m.RespawnSeconds+' s']));
const fieldGuide=referenceArticle({id:'field-guide',title:'Field colors & resources',summary:'Compare flower color mixes and open each field’s gathering reward table.',image:'flower.png',imageLabel:'Flower artwork',facts:[['Playable fields',playerFields.length],['Colors','White · red · blue']],sections:[['Choosing a flower color','The table shows configured flower color proportions. These are field-generation targets, not a live count of flowers or a guarantee that every scoop contains the same mix.'],['Matching a bee’s color','Red and Blue bees receive a ×1.5 color multiplier when gathering from a flower of their own color. The checked gathering handler applies no equivalent white-flower match bonus to Colorless bees. Flower quality, remaining nectar, mutations, and other bonuses still affect the reward.'],['Resources are a separate table','Field colors describe flowers, not item drop rates. Open a field below to see its item-find table and the quests that mention it.']],related:['gathering','loot-guide','bees'],source:sourceLabel('Field floor color attributes and BeeAI gathering handler')});
tableFor(fieldGuide,'Flower mix',['Field','White','Red','Blue'],playerFields.map(f=>{const d=REFERENCE_DATA.fields[f.id];return [guideLink('field-'+slug(f.id)),...['white','red','blue'].map(c=>d?.[c]!==undefined?d[c]+'%':'Not yet recorded')]}),'Rounding can make a displayed row total slightly different from 100%.');
const playerRewards=referenceArticle({id:'player-level-rewards',title:'Player level rewards',summary:'See the item and honey rewards for player levels 1–10.',facts:[['Progression','Player levels'],['Different from','Bee experience']],sections:[['Player levels and bee levels are separate','These rewards belong to player progression. Feeding XP levels an individual bee; it does not describe the player-level reward track. Use the bee level table for feeding requirements.'],['Read each reward as a bundle','A row lists the full configured bundle for that level. Item links lead to their other documented sources and uses.']],related:['feeding-and-energy','bees','item-fallingstar'],source:sourceLabel('Player level reward configuration and acquisition reward handlers')});
tableFor(playerRewards,'Rewards by level',['Level','Honey','Item','Quantity'],AD.levels.flatMap((rewards,i)=>{const honey=rewards.find(r=>r.item.toLowerCase()==='honey')?.amount||0;return rewards.filter(r=>r.item.toLowerCase()!=='honey').map((r,n)=>[n===0?i+1:'',n===0?fmt(honey):'',itemCell(r.item),r.amount])}),'Honey is granted once per level bundle; it is shown only on the first row for each level.');
const equipmentGuide=referenceArticle({id:'equipment-planning',title:'Equipment costs & materials',summary:'Compare purchase costs and see which materials are needed for obtainable equipment.',facts:[['Shops','Starter · Rocky'],['Costs','Honey + materials']],sections:[['Read the full price','A honey price is only part of the cost when an item also lists materials. Material links show where to obtain them and which other purchases need them.'],['Two shoulders, two purchases','Left Mud Shoulder and Right Mud Shoulder each cost 2,500 honey, 12 Pins, and 3 Berry Chitin. Buying both costs 5,000 honey, 24 Pins, and 6 Berry Chitin in total.'],['Compare effects as well as rarity','Tools differ in nectar per flower, gathering patterns, cooldowns, and passives. Bags add capacity and may add their own effects. Rarity alone does not describe whether an item fits the role you want.']],related:['starter-shop','rocky-shop','equipment','item-pins','item-berrychitin'],source:sourceLabel('ShopManager, ToolConfig, BagsConfig, HatConfig and GearData')});
const obtainableGear=Object.values({...AD.tools,...AD.bags,...AD.hats,...AD.gear}).filter(v=>ARTICLES.some(a=>a.id===slug(v.DisplayName)&&a.category==='gear'));
tableFor(equipmentGuide,'Purchase requirements',['Equipment','Honey','Materials'],obtainableGear.map(v=>[guideLink(slug(v.DisplayName)),fmt(v.Price),costsText(v.ItemCosts)||'None']));
referenceArticle({id:'quest-guide',title:'Quest objectives & rewards',summary:'Understand objective wording, repeatable quests, seasonal quests, and reward bundles.',facts:[['Quest givers',ARTICLES.filter(a=>a.quests?.length).length],['Current quest entries',ARTICLES.reduce((n,a)=>n+(a.quests?.length||0),0)]],sections:[['Match the objective wording','Field objectives name where to gather. Color objectives name the nectar color. When a quest contains both, read them as separate requirements; one activity may contribute to more than one requirement.'],['Collecting and handing in','An objective asking for freshly collected items tracks new collection. A hand-in objective asks you to give items to the NPC. Keeping an old item in your inventory does not necessarily complete a fresh-collection objective.'],['Regular, repeatable, and seasonal quests','NPC pages label repeatable quests and seasonal questlines. The currently active Autumn Harvest quests have their own seasonal label and event currencies.'],['Reading an NPC page','Open the Quests tab, then expand a quest to see its requirements, rewards, and dialogue. Reward quantities are per completion; dialogue sections contain story spoilers.']],related:ARTICLES.filter(a=>a.quests?.length).map(a=>a.id),source:sourceLabel('Current NPC quest definitions and seasonal quest configuration')});
referenceArticle({id:'gathering',title:'Gathering & conversion',summary:'How tools, bees, flowers, capacity, and hive conversion work together.',image:'gathering.png',imageLabel:'Gathering artwork',facts:[['Bee color match','×1.5 for red / blue'],['Bag capacity','Limits stored nectar']],sections:[['Tools and bees gather separately','Tools define nectar per flower and a cooldown, while each bee has its own gather amount and gather time. A bee’s level scales its gather amount; it does not shorten the base gather duration.'],['Flowers have a remaining supply','Bee collection depends on how much nectar remains in the flower. If a flower is partially drained, the reward can be smaller than the bee’s listed gather amount. Flower multipliers, player bonuses, and mutations can also change the result.'],['Capacity is a real limit','A full backpack prevents the checked bee gathering action from completing. More capacity lets you hold more nectar; it does not directly raise the bee’s base gather amount.'],['Understanding conversion stats','Convert amount describes nectar converted per action, and convert time describes the action duration. Hive conversion aggregates the bees’ adjusted conversion contributions. Convert Rate, Convert Rate at Hive, and Additional Convert Amount can change the result.'],['Color and energy','Red and Blue bees get a ×1.5 match multiplier on their own flower color. Gathering also uses bee resources; the Food, energy & rest guide explains how exhausted bees recover.']],related:['field-guide','feeding-and-energy','equipment','bees'],source:sourceLabel('BeeAI, BeeService, ToolConfig and BagsConfig')});
// Enrich individual entries with exact, linked uses rather than generic item descriptions.
function addUse(rawId,target,detail){const a=publicItem(rawId);if(!a||!ARTICLES.some(x=>x.id===target))return;a.uses??=[];if(!a.uses.some(r=>r[0].id===target&&r[1]===detail))a.uses.push([guideLink(target),detail]);}
for(const v of obtainableGear)for(const [id,n] of Object.entries(v.ItemCosts||{}))addUse(id,slug(v.DisplayName),fmt(n)+' required per purchase.');
for(const b of AVAILABLE_BEES)addUse(b.FavoriteFoodId,slug(b.DisplayName),'Favorite food; can roll ascension while this bee is not ascended.');
for(const [id,d] of publicFood)addUse(id,'feeding-and-energy',d.maxEnergy?'Permanently adds +1 maximum energy; shared +15 food bonus cap.':d.xp+' XP and '+(d.energy??1)+' current energy per item.');
if(autumnAvailable)for(const offer of AD.autumnOffers)for(const [id,n] of Object.entries(offer.Costs))addUse(id,'autumn-shop',offer.Name+': '+fmt(n)+' required per offer.');
for(const id of ['egg_normal','egg_diamond','egg_rainbow'])addUse(id,'bees','Hatch a bee; see this egg’s rarity probabilities.');
addUse('Jel','bees','Reroll a bee; see the Jel rarity probabilities.');
for(const a of ARTICLES){if(a.uses?.length){tableFor(a,'Used for',['Bee / activity / equipment','Use'],a.uses,'Confirmed uses documented by this wiki; this list may not cover every use.');a.related.push(...a.uses.slice(0,5).map(row=>row[0].id));}if(a.category==='abilities'){const id=WIKI_CATALOG.abilities.find(t=>'ability-'+slug(t.id)===a.id)?.id;const d=BEE_GUIDE_DATA.tokens[id],p=BEE_GUIDE_DATA.policies[id];if(d){a.facts=[['Token lifetime',d.lifetime+' s'],['Context',(d.categories||[]).join(', ')],...(p?[['Eligible attempt chance',Number((p.chance*100).toFixed(3))+'%'],['Attempt interval',p.interval+' s'],['Cooldown',p.cooldown+' s']]:[])];a.sections.push(['Timing','These are base timing values. Attempts require the appropriate context and an expired cooldown. Ability Rate and competing abilities can change how often the token actually appears.']);a.related.push(...AVAILABLE_BEES.filter(b=>b.AbilityIds.includes(id)).map(b=>slug(b.DisplayName)));a.source=sourceLabel('Token families, TokenDefinition and BeeRollService');}}if(a.category==='fields'){const raw=playerFields.find(f=>'field-'+slug(f.id)===a.id);const d=REFERENCE_DATA.fields[raw?.id];if(d){tableFor(a,'Flower colors',['Color','Configured share'],[['White',d.white+'%'],['Red',d.red+'%'],['Blue',d.blue+'%']],'Field-generation proportions; the live flower mix can vary.');a.related.push('field-guide','loot-guide');}}}

for(const b of AVAILABLE_BEES){const a=ARTICLES.find(a=>a.id===slug(b.DisplayName));const peers=AVAILABLE_BEES.filter(x=>x.Rarity===b.Rarity).length;const rows=['egg_normal','egg_diamond','egg_rainbow'].filter(id=>publicItem(id)).map(id=>{const weights=BEE_GUIDE_DATA.eggs[id].RarityWeights;const total=Object.values(weights).reduce((n,v)=>n+v,0);const chance=100*(weights[b.Rarity]||0)/total/peers;return [itemCell(id),Number(chance.toFixed(4))+'%']});const jelly={Regular:55,Uncommon:25,Rare:15,Epic:4.9,Legendary:.1};if(publicItem('Jel'))rows.push([itemCell('Jel'),Number((jelly[b.Rarity]/peers).toFixed(4))+'%']);tableFor(a,'Obtaining this bee',['Direct hatch / reroll','Chance of this bee'],rows,'Direct hatching and standard Jel select uniformly among eligible bees of the rolled rarity. Percentages are for this specific bee, rounded to four decimals. Egg smashing uses different luck rules.');a.related.push('favorite-foods','feeding-and-energy');}
const publicIds=new Set(ARTICLES.map(a=>a.id));
for(const a of ARTICLES){a.related=[...new Set(a.related)].filter(id=>publicIds.has(id)||CATEGORIES.some(c=>c[0]===id));for(const t of a.tables||[])for(const row of t.rows)for(let i=0;i<row.length;i++)if(row[i]&&typeof row[i]==='object'&&row[i].id&&!publicIds.has(row[i].id))row[i]={text:row[i].text};}
CATEGORIES.find(c=>c[0]==='mechanics')[1]='Guides & Mechanics';
CATEGORY_COPY.mechanics='Food, energy, field colors, rewards, equipment costs, and the systems behind them.';
const REFERENCE_GUIDES=['feeding-and-energy','favorite-foods','field-guide','loot-guide','equipment-planning','player-level-rewards'];
