function guideHub(){return '<section class="reference-hub"><div class="reference-hub-heading"><h2>Explore the game</h2><a href="#mechanics">All reference guides →</a></div><div class="reference-hub-grid">'+REFERENCE_GUIDES.map((id,i)=>{const a=ARTICLES.find(a=>a.id===id);return '<a class="reference-hub-card" href="#'+id+'"><span class="reference-number">0'+(i+1)+'</span><h3>'+esc(a.title)+'</h3><p>'+esc(a.summary)+'</p><span class="reference-arrow" aria-hidden="true">↗</span></a>'}).join('')+'</div></section>';}
function referenceWidgets(a){if(a.id==='feeding-and-energy')return '<section class="reference-calculator"><h2>Food XP calculator</h2><p>Enter the bee’s total XP to estimate how much food reaches your target level.</p><div class="calculator-inputs"><label>Current total XP<input id="food-current-xp" type="number" min="0" max="9007199254740991" step="1" value="0"></label><label>Target bee level<select id="food-target-level">'+BEE_GUIDE_DATA.levels.map((_,i)=>'<option value="'+(i+1)+'" '+(i===5?'selected':'')+'>Level '+(i+1)+'</option>').join('')+'</select></label><label>Food<select id="food-choice">'+publicFood.filter(([id,d])=>d.xp>0).map(([id,d])=>'<option value="'+esc(id)+'" '+(id==='Treat'?'selected':'')+'>'+esc(d.name)+'</option>').join('')+'</select></label></div><output id="food-result" class="calculator-result" aria-live="polite"></output><p class="guide-note">Uses the configured XP per food. Counts round up; any extra XP in the last food is included.</p></section>';if(a.id==='favorite-foods')return '<section class="reference-calculator"><h2>Favorite-food chance calculator</h2><p>Chance of at least one ascension from a batch of matching favorite food.</p><div class="calculator-inputs"><label>Bee rarity<select id="ascension-rarity">'+Object.keys(REFERENCE_DATA.ascensionOneIn).map(r=>'<option>'+r+'</option>').join('')+'</select></label><label>Food consumed<input id="ascension-amount" type="number" min="1" max="1000000" step="1" value="100"></label></div><output id="ascension-result" class="calculator-result" aria-live="polite"></output><p class="guide-note">Applies only to a non-ascended bee consuming its own favorite food. This estimates chance, not a guaranteed result.</p></section>';return '';}
function foodEstimate(xp,target,food){const threshold=BEE_GUIDE_DATA.levels[target-1];const gain=REFERENCE_DATA.foods[food]?.xp;if(!Number.isSafeInteger(xp)||xp<0||!Number.isInteger(target)||threshold===undefined||!gain)return null;const remaining=Math.max(0,threshold-xp);const count=Math.ceil(remaining/gain);return {remaining,count,total:xp+count*gain};}
function ascensionEstimate(rarity,amount){const oneIn=REFERENCE_DATA.ascensionOneIn[rarity];if(!oneIn||!Number.isInteger(amount)||amount<1||amount>1000000)return null;return -Math.expm1(amount*Math.log1p(-1/oneIn))*100;}
function bindReference(a,key){if(key!=='overview')return;
 const foodResult=document.getElementById('food-result');if(foodResult){const update=()=>{const input=document.getElementById('food-current-xp'),target=document.getElementById('food-target-level'),food=document.getElementById('food-choice');const r=input.value===''?null:foodEstimate(Number(input.value),Number(target.value),food.value);foodResult.textContent=r?(r.count===0?'Target level already reached.':number(r.count)+' '+itemName(food.value)+' · '+number(r.remaining)+' XP needed · '+number(r.total)+' total XP after feeding'):'Enter a non-negative whole XP value.'};['food-current-xp','food-target-level','food-choice'].forEach(id=>document.getElementById(id).addEventListener('input',update));update();}
 const ascensionResult=document.getElementById('ascension-result');if(ascensionResult){const update=()=>{const value=ascensionEstimate(document.getElementById('ascension-rarity').value,Number(document.getElementById('ascension-amount').value));ascensionResult.textContent=value===null?'Enter a whole food count between 1 and 1,000,000.':value.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:4})+'% chance of at least one ascension';};['ascension-rarity','ascension-amount'].forEach(id=>document.getElementById(id).addEventListener('input',update));update();}
 if(a.category==='mechanics'||a.category==='items'){const headings=[...document.querySelectorAll('#article-content h2')];if(headings.length>=3){const nav=document.createElement('nav');nav.className='article-contents';nav.setAttribute('aria-label','On this page');nav.innerHTML='<span>On this page</span>'+headings.map((h,i)=>{h.id='reference-section-'+i;h.tabIndex=-1;return '<button data-reference-section="'+h.id+'">'+esc(h.textContent)+'</button>'}).join('');document.getElementById('article-content').prepend(nav);nav.querySelectorAll('button').forEach(btn=>btn.onclick=()=>{const target=document.getElementById(btn.dataset.referenceSection);target.focus({preventScroll:true});target.scrollIntoView({block:'start',behavior:'instant'})});}}
}
